- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format
  entry: terraform-fmt.sh
  language: python
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true
